package com.example.demo;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class PdfHeaderFooter extends PdfPageEventHelper {

    private Image logo;

    public PdfHeaderFooter() {
        try {
            java.net.URL imageUrl = getClass().getClassLoader().getResource("logo.png");
            if (imageUrl == null) {
                throw new IOException("Logo not found in classpath");
            }
            logo = Image.getInstance(imageUrl);
            logo.scaleToFit(50, 50);
        } catch (IOException | BadElementException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onStartPage(PdfWriter writer, Document document) {
        try {
            PdfPTable header = new PdfPTable(2);
            header.setWidths(new int[]{1, 4});
            header.setTotalWidth(527);
            header.setLockedWidth(true);
            header.getDefaultCell().setFixedHeight(60);
            header.getDefaultCell().setBorder(Rectangle.BOTTOM);

            // Left: logo
            PdfPCell logoCell = new PdfPCell(logo, true);
            logoCell.setBorder(Rectangle.BOTTOM);
            logoCell.setHorizontalAlignment(Element.ALIGN_LEFT);
            header.addCell(logoCell);

            // Right: heading text
            PdfPCell text = new PdfPCell();
            text.setBorder(Rectangle.BOTTOM);
            text.addElement(new Phrase("IT-INFO ACADEMY", new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD)));
            text.addElement(new Phrase("2ND FLOOR, BLUE SAPPHIRE BUILDING NEAR KFC, \r\n"
            		+ "SANGLI-MIRAJ ROAD, VIJAYNAGAR, SANGLI.416415 ", new Font(Font.FontFamily.HELVETICA, 12)));
            header.addCell(text);
            
            header.writeSelectedRows(0, -1, 34, 803, writer.getDirectContent());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void onEndPage(PdfWriter writer, Document document) {
        PdfPTable footer = new PdfPTable(1);
        try {
            footer.setTotalWidth(527);
            footer.setLockedWidth(true);
            footer.getDefaultCell().setBorder(Rectangle.TOP);
            footer.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
            footer.getDefaultCell().setPaddingTop(5);

            String date = new SimpleDateFormat("dd MMM yyyy HH:mm").format(new Date());
            footer.addCell(new Phrase("Generated by IT-INFO Academy • " + date,
                    new Font(Font.FontFamily.HELVETICA, 9)));

            footer.writeSelectedRows(0, -1, 34, 30, writer.getDirectContent());
        } catch (Exception de) {
            throw new ExceptionConverter(de);
        }
    }
}
